# detox.conf — Configuration for detox.sh

# shellcheck disable=SC2034
RED="\033[0;31m"
GREEN="\033[0;32m"
YELLOW="\033[0;33m"
BLUE="\033[0;34m"
CLEAN="\033[0;36m"
RESET="\033[0m"

# shellcheck disable=SC2034
PERL_BINARY_REGEX='s/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]//g'
PERL_ZWC_REGEX='s/[\x{200B}\x{200C}\x{200D}\x{FEFF}]//g'
PERL_COMBINED_REGEX='s/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]//g; s/\x{200B}|\x{200C}|\x{200D}|\x{FEFF}//g'
